version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .docker.env
    ports:
      - "5442:5432"
    volumes:
      - data:/var/lib/postgresql/data
    container_name: db
    networks:
      - app-network
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapper
    volumes:
      - .:/app
    depends_on:
      - database
    networks:
      - app-network
    ports:
      - "8080:8080"

networks:
  app-network:
    driver: bridge
volumes:
  data:
